/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as IndexRouteImport } from './routes/index'

const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apresentacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apresentacao'
  id: '__root__' | '/' | '/apresentacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApresentacaoRoute: typeof ApresentacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApresentacaoRoute: ApresentacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
